remote_theme: yx-lu/minimal
title: Yuxuan Lu
description: "<body class='typora-export os-windows'><div class='typora-export-content'>
<div id='write'  class=''><p><span>âœ‰ï¸ yx_lu [at] pku.edu.cn</span></p><p><span>ğŸ§» </span><a href='https://scholar.google.com/citations?hl=en&amp;user=w8h0b0EAAAAJ'><span>Google scholar</span></a></p></div></div>"
logo: img/mainphoto.jpg

